#!/usr/bin/env bash

if [ "$(uname)" == "Darwin" ]; then
	# Do something under Mac OS X platform
	brew install ctags
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
        # Do something under GNU/Linux platform
	sudo apt-get install -y exuberant-ctags
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    	# Do something under Windows NT platform
	echo Win
fi
